name: Obtain latest hearings data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *' # 7:00 PM GMT, which is 3:00 AM GMT+8

jobs:
  hearings:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Specify the Python version you need

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch latest data
        run: python input/hearings/get_hearings.py

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated update"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(TZ='Asia/Singapore' date)
          git commit -m "Latest hearings data: ${timestamp}" || exit 0
          git pull --rebase
          git push
